### PR TITLE
Updating to debian:jessie

### PR DESCRIPTION
**Pull request by rheinwein**
Updating from wheezy to jessie.

### CODE REVIEW

**Comment by beanieboi** [comment]
LGTM

**Comment by ngauthier** [comment]
Nice!

**Comment by ngauthier** [comment]
I am merging in, since phantomjs 2.0 needs jessie for dynamic linking

**Comment by ngauthier** [comment]
I'll push this to the hub as codeship/ruby:2.2.3-jessie

**Pull request merged**
